# Generated by Django 5.2.5 on 2025-09-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhoneHub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonemodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
